// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ITWareDbContext))]
    [Migration("20240919071931_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true);

            modelBuilder.Entity("ApplicationCore.Entities.EquipmentAggregate.Equipment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BarCode")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Count")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NetworkName")
                        .HasColumnType("TEXT");

                    b.Property<string>("SNL")
                        .HasColumnType("TEXT");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("LocationId");

                    b.ToTable("Equipment");
                });

            modelBuilder.Entity("ApplicationCore.Entities.EquipmentAggregate.EquipmentCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("EquipmentCategory");
                });

            modelBuilder.Entity("ApplicationCore.Entities.LocationAggregate.Area", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BuildingId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.ToTable("Area");
                });

            modelBuilder.Entity("ApplicationCore.Entities.LocationAggregate.BaseLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Locations");

                    b.HasDiscriminator().HasValue("BaseLocation");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("ApplicationCore.Entities.LocationAggregate.Building", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Building");
                });

            modelBuilder.Entity("ApplicationCore.Entities.LocationAggregate.Rack", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BarCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Rack");
                });

            modelBuilder.Entity("ApplicationCore.Entities.LocationAggregate.Shelf", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BarCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RackId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RackId");

                    b.ToTable("Shelf");
                });

            modelBuilder.Entity("ApplicationCore.Entities.LocationAggregate.InUseLocation", b =>
                {
                    b.HasBaseType("ApplicationCore.Entities.LocationAggregate.BaseLocation");

                    b.Property<Guid>("AreaId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BuildingId")
                        .HasColumnType("TEXT");

                    b.HasIndex("AreaId");

                    b.HasIndex("BuildingId");

                    b.HasDiscriminator().HasValue("InUseLocation");
                });

            modelBuilder.Entity("ApplicationCore.Entities.LocationAggregate.StoredLocation", b =>
                {
                    b.HasBaseType("ApplicationCore.Entities.LocationAggregate.BaseLocation");

                    b.Property<Guid>("RackId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ShelfId")
                        .HasColumnType("TEXT");

                    b.HasIndex("RackId");

                    b.HasIndex("ShelfId");

                    b.HasDiscriminator().HasValue("StoredLocation");
                });

            modelBuilder.Entity("ApplicationCore.Entities.EquipmentAggregate.Equipment", b =>
                {
                    b.HasOne("ApplicationCore.Entities.EquipmentAggregate.EquipmentCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApplicationCore.Entities.LocationAggregate.BaseLocation", "Location")
                        .WithMany("Equipment")
                        .HasForeignKey("LocationId");

                    b.Navigation("Category");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("ApplicationCore.Entities.LocationAggregate.Area", b =>
                {
                    b.HasOne("ApplicationCore.Entities.LocationAggregate.Building", "Building")
                        .WithMany("Areas")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Building");
                });

            modelBuilder.Entity("ApplicationCore.Entities.LocationAggregate.Shelf", b =>
                {
                    b.HasOne("ApplicationCore.Entities.LocationAggregate.Rack", "Rack")
                        .WithMany("Shelves")
                        .HasForeignKey("RackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rack");
                });

            modelBuilder.Entity("ApplicationCore.Entities.LocationAggregate.InUseLocation", b =>
                {
                    b.HasOne("ApplicationCore.Entities.LocationAggregate.Area", "Area")
                        .WithMany()
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApplicationCore.Entities.LocationAggregate.Building", "Building")
                        .WithMany()
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("Building");
                });

            modelBuilder.Entity("ApplicationCore.Entities.LocationAggregate.StoredLocation", b =>
                {
                    b.HasOne("ApplicationCore.Entities.LocationAggregate.Rack", "Rack")
                        .WithMany()
                        .HasForeignKey("RackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApplicationCore.Entities.LocationAggregate.Shelf", "Shelf")
                        .WithMany()
                        .HasForeignKey("ShelfId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rack");

                    b.Navigation("Shelf");
                });

            modelBuilder.Entity("ApplicationCore.Entities.LocationAggregate.BaseLocation", b =>
                {
                    b.Navigation("Equipment");
                });

            modelBuilder.Entity("ApplicationCore.Entities.LocationAggregate.Building", b =>
                {
                    b.Navigation("Areas");
                });

            modelBuilder.Entity("ApplicationCore.Entities.LocationAggregate.Rack", b =>
                {
                    b.Navigation("Shelves");
                });
#pragma warning restore 612, 618
        }
    }
}
